file(REMOVE_RECURSE ${CMAKE_BINARY_DIR}/CMakeFiles)
file(REMOVE ${CMAKE_BINARY_DIR}/CMakeCache.txt)
file(REMOVE ${CMAKE_BINARY_DIR}/cmake_install.cmake)
file(REMOVE ${CMAKE_BINARY_DIR}/Makefile)
file(REMOVE ${CMAKE_BINARY_DIR}/LearningRaylib.exe)
